export const employees = [
  {
    id: 1,
    email: 'viktor-tasevski@hotmail.com',
    password: '123',
    firstName: 'Viktor',
    lastName: 'Tasevski',
    zones: ['Zona 1', 'Zona 2', 'Zone 4'],
    phoneNumber: '072500000',
    status: 'vacation',
    accountActive: true,
  },
  {
    id: 2,
    email: 'andrejTav@gmail.com',
    password: '123',
    firstName: 'Andrej',
    lastName: 'Tavcioski',
    zones: ['Zona 2', 'Zona 5'],
    phoneNumber: '070350123',
    status: 'working',
    accountActive: true,
  },
  {
    id: 3,
    email: 'david.trajkovski@yahoo.com',
    password: '123',
    firstName: 'David',
    lastName: 'Trajkovski',
    zones: ['Zona 3'],
    phoneNumber: '078123321',
    status: 'working',
    accountActive: true,
  },
  {
    id: 4,
    email: 'poc@gmail.com',
    password: '123',
    firstName: 'Nekoj od',
    lastName: 'POC',
    zones: ['Zona 4'],
    phoneNumber: '223305',
    status: 'notWorking',
    accountActive: true,
  },
  {
    id: 5,
    email: 'silbo@outlook.com',
    password: '123',
    firstName: 'Nekoj od',
    lastName: 'Silbo',
    zones: [],
    phoneNumber: '071206205',
    status: 'sick',
    accountActive: false,
  },
];
